user:
  name:
    length: 50
  email:
    length: 50
    case_sensitive: false
  password:
    length: 6
  gravatar:
    size: 80
  per_page: 10
  reset_password:
    expire: 2
microposts:
  content:
    max_length: 140
  upload_max_size: 5
